dist: bionic

language: python

matrix:
  include:
    - python: 3.7

before_install:
  - source ci/java_install.sh

install:
  - poetry install
  - poetry run ruff check
  - poetry run pylint --output-format=colorized --fail-under=8 src/ tests/
  - poetry run pycodestyle --config pycodestyle.ini src/ tests/
  - poetry run pytest
  - poetry build

script:
  - tox
